### ISSUE TITLE
能否支持 WebSocket?

### ISSUE THREAD

**Issue by k79e** [Berkeley-Reject/Workers-Proxy#25]
测了下发现不支持
应该是4个头部没通过

> connection
> upgrade
> Sec-WebSocket-Key
> Sec-WebSocket-Version

是这样的 不加头部的话 显示的是报错 就是ws的普通报错.
加了头部测试的话 他说我访问的资源在cf网络上. 渲染页面的时候有个未知错误发生了
You've requested a page on a website (xxxxxx) that is on the Cloudflare network. An unknown error occurred while rendering the page.

我把反代挂到webhook上一看 4个头部是被传递的. 看起来是其他地方出问题了....

**Comment by Berkeley-Reject** [comment]
看起来是以前的版本修改了 WebSocket 的 Headers 导致连接失败, 最新版本解决了这个问题.
用该项目搭建了一个 [WebSocket Echo Server](http://echo.websocket.org/) 反向代理: [https://ws.xasiimov.workers.dev](https://ws.xasiimov.workers.dev/)
欢迎测试.

**Comment by Berkeley-Reject** [comment]
测试了一下 V2Ray WebSocket 转发, 可以正常使用了.

**Comment by ZhaoUncle** [comment]
websocket好像又无法支持了？
