### ISSUE TITLE
反代 Google Scholar 出现异常流量错误

### ISSUE THREAD

**Issue by yanyuechuixue** [Berkeley-Reject/Workers-Proxy#27]
**Describe the bug**
使用的是 ```wrangler generate my-proxy https://github.com/Siujoeng-Lau/Workers-Proxy``` 中的例子，除 ```wrangler.toml``` 外，没有经过任何修改

**To Reproduce**
Steps to reproduce the bug.

``` bash
wrangler generate my-proxy https://github.com/Siujoeng-Lau/Workers-Proxy
wrangler config
vim wrangler.toml #write the zone_id and account_id
vim src/index.js # replace the headers with examples/google-scholar
wrangle build
wrangle publish

```

**Screenshots**
```
关于此网页

我们的系统检测到您的计算机网络中存在异常流量。此网页用于确认这些请求是由您而不是自动程序发出的。为什么会这样？


IP 地址：172.68.46.178
时间：2020-04-02T04:01:51Z
网址：https://scholar.google.com/
```
**Additional context**

**Comment by Siujoeng-Lau** [comment]
试试反代其他网站
可能是 Cloudflare 的 IP 被 Google 拉黑了导致的
参考: https://www.v2ex.com/t/271860

**Comment by yanyuechuixue** [comment]
多谢!

**Comment by cakexxx** [comment]
关键是有时候验证码都不出来直接显示和密钥不符，问一下有没有可能通过自己申请的reCAPTCHA 的API让验证码能正常显示呢？ 我也只是在网上查到的，不知道能不能实现？

**Comment by Berkeley-Reject** [comment]
> 关键是有时候验证码都不出来直接显示和密钥不符，问一下有没有可能通过自己申请的reCAPTCHA 的API让验证码能正常显示呢？ 我也只是在网上查到的，不知道能不能实现？

我申请了一个 reCAPTCHA v2 的 Key, 做了一下文本替换. 现在验证码可以正常显示, 但是通过验证后还是没法查看搜索结果...
[测试](cdn.reverse-proxy.live)

**Comment by cakexxx** [comment]
> > 关键是有时候验证码都不出来直接显示和密钥不符，问一下有没有可能通过自己申请的reCAPTCHA 的API让验证码能正常显示呢？ 我也只是在网上查到的，不知道能不能实现？
> 
> 我申请了一个 reCAPTCHA v2 的 Key, 做了一下文本替换.
> 现在验证码可以正常显示, 但是通过验证后还是没法查看搜索结果...
> [测试页面 (www.google.com)](cdn.reverse-proxy.live)

可以说一下如何做文本替换嘛？感谢~

**Comment by Berkeley-Reject** [comment]
> > > 关键是有时候验证码都不出来直接显示和密钥不符，问一下有没有可能通过自己申请的reCAPTCHA 的API让验证码能正常显示呢？ 我也只是在网上查到的，不知道能不能实现？
> > 
> > 
> > 我申请了一个 reCAPTCHA v2 的 Key, 做了一下文本替换.
> > 现在验证码可以正常显示, 但是通过验证后还是没法查看搜索结果...
> > [测试页面 (www.google.com)](cdn.reverse-proxy.live)
> 
> 可以说一下如何做文本替换嘛？感谢~

1. 修改 index.js:
```
const replace_dict = {
    '$upstream': '$custom_domain',
    'Google 验证码 Key': '自己申请的 Key'
}
```
2. 把 103 行改成:
`if (content_type != null && content_type.includes('text/html')) {`

**Comment by cakexxx** [comment]
问一下有解决方案了吗？

**Comment by Berkeley-Reject** [comment]
> 问一下有解决方案了吗？

试了一下换成自己生成的验证码 Key, 这样还是无法通过验证...

**Comment by cakexxx** [comment]
> > 问一下有解决方案了吗？
> 
> 试了一下换成自己生成的验证码 Key, 这样还是无法通过验证...

好吧，谢谢
