### ISSUE TITLE
Issues with pornhub

### ISSUE THREAD

**Issue by YuutaDoNo** [Berkeley-Reject/Workers-Proxy#30]
Can't load page without const upstream_path = '/'. Cloudflare shows ERROE 1011.

Page recycling redrict with &utm_medium=redirects&utm_campaign=hotlinkerredirects if I add upstream_path.

**Comment by Berkeley-Reject** [comment]
const upstream_path = '/'
这个不能删掉啊...

**Comment by YuutaDoNo** [comment]
但是在不删除的情况下，就会出现第二行中提到的无限跳转。

**Comment by Berkeley-Reject** [comment]
我测试了一下也不行... 似乎反代网站会尝试跳转回原站.

**Comment by YuutaDoNo** [comment]
能否实现类似nginx sub_filter的功能，将网站html header中的跳转script禁用。

**Comment by YuutaDoNo** [comment]
以通过replace texts模块修复无法正常访问的问题
```
    'var scriptText': '',
```

**Comment by Berkeley-Reject** [comment]
感谢反馈. 已经更新示例.
