### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'toUpperCase' of null

### ISSUE THREAD

**Issue by DeSireFire** [Berkeley-Reject/Workers-Proxy#36]
**Describe the bug**
Uncaught (in promise) TypeError: Cannot read property 'toUpperCase' of null.

**To Reproduce**
直接复制 [这里](https://raw.githubusercontent.com/Berkeley-Reject/Workers-Proxy/master/src/index.js)的代码想看看谷歌的反代效果

**Screenshots**
![image](https://user-images.githubusercontent.com/18726905/82081137-6522a500-9718-11ea-9f6b-096072772f96.png)

**Additional context**
请问这是什么原因造成的？我搜了也不知道怎么解决，跑来搜issue好像也没问过有关toUpperCase关键词的问题，于是就问一下。2333

**Comment by Berkeley-Reject** [comment]
选一下 "预览" 试试.

**Comment by DeSireFire** [comment]
> 选一下 "预览" 试试.

....啊，能打开。行吧，我是智障（

那个用调试的话，报错是什么原因？
因为JS没有能够加载么

**Comment by Berkeley-Reject** [comment]
> > 选一下 "预览" 试试.
> 
> ....啊，能打开。行吧，我是智障（
> 
> 那个用调试的话，报错是什么原因？
> 因为JS没有能够加载么

调试时不会向 Worker 发送判断国家或地区的 header, 所以就报错了...
