### ISSUE TITLE
Sites are refreshing continuosly

### ISSUE THREAD

**Issue by viper-adnan** [Berkeley-Reject/Workers-Proxy#37]
Hey, I made a proxy of pornhub sites but when I open it, it refreshing continuosly.

**https://new.npa.workers.dev**
Here is the site domain.

**Comment by Berkeley-Reject** [comment]
Basically there's a script in the header of the site which will cause this issue. (Issue: #30; Commit: 38b19a7bb8eee96fda46cdd144ba6b948e17e148)
You may use this [example configuration](https://github.com/Berkeley-Reject/Workers-Proxy/blob/master/examples/pornhub/www.pornhub.com) to set up the proxy, in which that script is removed.
